[build]
  # Build command for React + Vite
  command = "npm run build"
  
  # Output directory after build
  publish = "dist"

[build.environment]
  # Ensure Node.js version compatibility
  NODE_VERSION = "18"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy cloud backend to avoid CORS in production
[[redirects]]
  from = "/api-cloud/*"
  to = "https://statethon-fastapi-backend.onrender.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api-cloud/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Headers for better security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"